sharding:
  clusterRole: configsvr
replication:
  replSetName: config-server-replica-set
net:
  bindIp: localhost
  port: 21002
systemLog:
   destination: file
   path: "/home/ec2-user/localdbcluster/log/configserver/02/mongod.log"
   logAppend: true
storage:
   wiredTiger:
      engineConfig:
         cacheSizeGB: 2
   dbPath: "/home/ec2-user/localdbcluster/data/configserver/02"
   journal:
      enabled: true
processManagement:
   fork: true
